dist: trusty
git:
  depth: 3

branches:
  only:
    - stable
    - beta
    - beta5
    - feature/beta/.*

language: node_js
node_js:
  - 12

cache: npm

jobs:
  include:
    - name: 'Lint SCSS files'
      script: npm run lint:sass
    - name: 'Run test scripts'
      script: npm run test
    - name: 'Build assets'
      script: npm run build